#!/bin/csh
#
# DropDB
#
if ($1 == "" || $2 == "") then
  echo " "
  echo Usage: "$0 <Database Name> <SA password>"
  echo " "
  exit
endif
sed -e "s/<DATABASENAME>/$1/g" DropDB.script > foo
./irun.11.5.1 $2 foo
rm foo
