#!/bin/csh
#
# FillTables
#
if ($1 == "" || $2 == "" || $3 == "" ) then
  echo " "
  echo Usage: "$0 <DIM> <Database Name> <SA password>"
  echo " "
  exit
endif
sed -e "s/<DATABASENAME>/$2/g" Fill$1Tables.script > foo
irun.11.5.1 $3 foo
rm foo
