#!/bin/csh
#
# ListTables
#
if ($1 == "" || $2 == "" || $3 == "") then
  echo " "
  echo Usage: "$0 <DIM|Control> <Database Name> <SA Password>"
  echo " "
  exit
endif
sed -e "s/<DATABASENAME>/$2/g" List$1Tables.script > foo
irun.11.5.1 $3 foo
rm foo
