#!/bin/csh
#
# PrintTables
#
if ($1 == "" || $2 == "" || $3 == "" ) then
  echo " "
  echo Usage: "$0 <DIM|DIMSeries|Control|FIS> <Database Name> <SA Password>"
  echo " "
  exit
endif
sed -e "s/<DATABASENAME>/$2/g" Print$1Tables.script > foo
irun.11.5.1 $3 foo
rm foo
