
char *classes[][2] ={
{"VERIFICATION",DICOM_SOPCLASSVERIFICATION},		

{"COMPUTED  RADIOGRAPHY",DICOM_SOPCLASSCOMPUTEDRADIOGRAPHY},	
{"CT",DICOM_SOPCLASSCT},			
{"US MULTI  FRAME  IMAGE",DICOM_SOPCLASSUSMULTIFRAMEIMAGE},		
{"MR",DICOM_SOPCLASSMR},			
{"NM",DICOM_SOPCLASSNM},			
{"US",DICOM_SOPCLASSUS},			
{"SECONDARY  CAPTURE",DICOM_SOPCLASSSECONDARYCAPTURE},


{"PATIENT  QUERY_FIND",DICOM_SOPPATIENTQUERY_FIND},		
{"PATIENT  QUERYE_MOVE",DICOM_SOPPATIENTQUERY_MOVE},		
{"PATIENT  QUERY_GET",DICOM_SOPPATIENTQUERY_GET},		

{"STUDY  QUERY_FIND",DICOM_SOPSTUDYQUERY_FIND},		
{"STUDY  QUERY_MOVE",DICOM_SOPSTUDYQUERY_MOVE},		
{"STUDY  QUERY_GET",DICOM_SOPSTUDYQUERY_GET},			

{"PATIENT  STUDY  QUERY_FIND",DICOM_SOPPATIENTSTUDYQUERY_FIND},		
{"PATIENT  STUDY  QUERY_MOVE",DICOM_SOPPATIENTSTUDYQUERY_MOVE},		
{"PATIENT  STUDY  QUERY_GET",DICOM_SOPPATIENTSTUDYQUERY_GET},	

{"DETACHED  PATIENT  MGMT",DICOM_SOPCLASSDETACHEDPATIENTMGMT},
{"DETACHED  PATIENT  MGMT  META",DICOM_SOPCLASSDETACHEDPATIENTMGMTMETA},	
{"DETACHED  VISIT  MGMT",DICOM_SOPCLASSDETACHEDVISITMGMT},		
{"DETACHED  STUDY  MGMT",DICOM_SOPCLASSDETACHEDSTUDYMGMT},		
{"DETACHED  RESULTS  MGMT",DICOM_SOPCLASSDETACHEDRESULTSMGMT},	
{"DETACHED  RESULTS  MGMT  META",DICOM_SOPCLASSDETACHEDRESULTSMGMTMETA},	
{"DETACHED  STUDY  MGMT  META",DICOM_SOPCLASSDETACHEDSTUDYMGMTMETA},	
{"DETACHED  INTERPRETATION  MGMT",DICOM_SOPCLASSDETACHEDINTERPRETMGMT},	
	
{"STUDY  COMPONENT  MGMT",DICOM_SOPCLASSSTUDYCOMPONENTMGMT},	
 
	
{"GREY  SCALE  PRINT  MGMT  META",DICOM_SOPCLASSGREYSCALEPRINTMGMTMETA},	
{"COLOR  PRINT  MGMT  META",DICOM_SOPCLASSCOLORPRINTMGMTMETA},	

{"REFERENCED  GREY  SCALE  PRINT  MGMT  META",DICOM_SOPCLASSREFGREYSCALEPRINTMGMTMETA},	
{"REFERENCED  COLOR  PRINT  MGMT  META",DICOM_SOPCLASSREFCOLORPRINTMGMTMETA},
	
{"PRINT  JOB",DICOM_SOPCLASSPRINTJOB},					
};	

