#!/bin/csh
#
# DropTables
#
if ( $1 == "" || $2 == "" ) then
  echo " "
  echo Usage: "$0 <DIM|Control|TBLTest|FIS> <Database Name>"
  echo " "
  exit
endif
mysql -uctn -pctn $2 < Drop$1Tables.script
if ($status != 0) then
  echo Could not drop database: $1
  exit 1
endif
