#!/bin/csh
#
# DropDB
#
if ($1 == "") then
  echo " "
  echo Usage: "$0 <Database Name>"
  echo " "
  exit
endif
mysqladmin -uctn -pctn drop $1
if ($status != 0) then
  echo Could not drop database: $1
  exit 1
endif
