mkdir ..\..\include
copy ..\..\apps\apps_include\*.h ..\..\include
copy ..\..\facilities\cfg\*.h ..\..\include
copy ..\..\facilities\chr\*.h ..\..\include
copy ..\..\facilities\condition\*.h ..\..\include
copy ..\..\facilities\database\*.h ..\..\include
copy ..\..\facilities\ddr\*.h ..\..\include
copy ..\..\facilities\dicom\*.h ..\..\include
copy ..\..\facilities\snp\*.h ..\..\include
copy ..\..\facilities\dulprotocol\*.h ..\..\include
copy ..\..\facilities\gq\*.h ..\..\include
copy ..\..\facilities\hap\*.h ..\..\include
copy ..\..\facilities\fis\*.h ..\..\include
copy ..\..\facilities\his\*.h ..\..\include
copy ..\..\facilities\hunks\*.h ..\..\include
copy ..\..\facilities\iap\*.h ..\..\include
copy ..\..\facilities\icpy\*.h ..\..\include
copy ..\..\facilities\idb\*.h ..\..\include
copy ..\..\facilities\idbmb\*.h ..\..\include
copy ..\..\facilities\icon\*.h ..\..\include
copy ..\..\facilities\iman\*.h ..\..\include
copy ..\..\facilities\info_entity\*.h ..\..\include
copy ..\..\facilities\irs\*.h ..\..\include
copy ..\..\facilities\lst\*.h ..\..\include
copy ..\..\facilities\manage\*.h ..\..\include
copy ..\..\facilities\messages\*.h ..\..\include
copy ..\..\facilities\motif_util\*.h ..\..\include
copy ..\..\facilities\objects\*.h ..\..\include
copy ..\..\facilities\print\*.h ..\..\include
copy ..\..\facilities\services\*.h ..\..\include
copy ..\..\facilities\sq\*.h ..\..\include
copy ..\..\facilities\tbl\*.h ..\..\include
copy ..\..\facilities\tblmb\*.h ..\..\include
copy ..\..\facilities\thread\*.h ..\..\include
copy ..\..\facilities\uid\*.h ..\..\include
copy ..\..\facilities\utility\*.h ..\..\include
copy ..\..\facilities\xutl\*.h ..\..\include

